application/courses/models.py
import peewee

from application.db import BaseModel
from application.users.models import User


class Course(BaseModel):
    name = peewee.CharField()
    professor = peewee.ForeignKeyField(User, backref='courses')
    capacity = peewee.IntegerField()

    @property
    def student_count(self):
        return self.enrollments.count()


Course.create_table()


class CourseEnrollment(BaseModel):
    student = peewee.ForeignKeyField(User, backref='courses')
    course = peewee.ForeignKeyField(Course, backref='enrollments')


CourseEnrollment.create_table()


class CourseDependency(BaseModel):
    dependant = peewee.ForeignKeyField(Course, backref='dependees')
    dependee = peewee.ForeignKeyField(Course, backref='dependants')


CourseDependency.create_table()

application/users/models.py
from enum import IntEnum, unique

import peewee

from application.db import BaseModel


@unique
class Role(IntEnum):
    Student = 0
    Professor = 1
    Staff = 2


class User(BaseModel):
    username = peewee.CharField()
    password = peewee.CharField()
    role = peewee.IntegerField()


User.create_table()

application/app.py
from typing import Optional

from flask import Flask, render_template, session

from application.users import views as user_views
from application.users.models import User, Role
from application.courses import views as course_views


app = Flask(
    __name__.partition('.')[0],
    static_folder='../static')

# would be private in a real life application
app.secret_key = 'a3ws4e6d5rgt7hy8uj9@#ZXE$VTBYw4es5dr6tfgyih'

app.register_blueprint(user_views.users)
app.register_blueprint(course_views.courses)


@app.route("/")
def home():
    current_user: Optional[User] = session.get('current_user')

    if current_user is not None:
        return {
            Role.Student: user_views.student_home,
            Role.Professor: user_views.professor_home,
            Role.Staff: user_views.staff_home
        }[current_user['role']]()

    return render_template('home.html.j2')

application/courses/views.py
from typing import Optional, List, Set

from flask import Blueprint, render_template, session, redirect, url_for, flash

from .models import Course, CourseEnrollment
from application.users.models import User


courses = Blueprint('courses', __name__, url_prefix='/courses')


@courses.route('/')
def home():
    all_courses = Course.select()
    return render_template('courses/home.html.j2', courses=all_courses)


@courses.route('/<int:id>')
def course_view(id):
    course: Optional[Course] = Course.select().where(Course.pk == id).first()

    if course is not None:
        current_user = session.get('current_user')
        is_enrolled = False
        pending_dependencies = set()

        if current_user is not None:
            current_user = User.get_by_id(current_user['id'])
            is_enrolled = CourseEnrollment.select() \
                .where(CourseEnrollment.student == current_user,
                       CourseEnrollment.course == course) \
                .count() != 0

            if not is_enrolled:
                pending_dependencies = cross_check_dependencies(current_user, course)

        return render_template(
            'courses/course_view.html.j2',
            course=course, is_enrolled=is_enrolled, current_user=current_user,
            pending_dependencies=[pd.name for pd in pending_dependencies])

    else:
        return '', 404


@courses.route('/<int:id>/enroll', methods=['POST'])
def course_enroll(id):
    course: Course = Course.select().where(Course.pk == id).first()
    user: Optional[User] = User.select().where(User.pk == session['current_user']['id']).first()

    if user is None:
        flash('You must be logged in to enroll into a course.', 'error')
        return redirect(url_for('home'))

    pending_dependencies = cross_check_dependencies(user, course)

    if course.student_count >= course.capacity:
        flash("This course has reached max capacity.", 'error')

    elif pending_dependencies:
        course_names: List[str] = [pd.name for pd in pending_dependencies]
        flash(
            "You must complete the course{} '{}' first."
                .format('s' if len(course_names) != 1 else '',
                        ', '.join(course_names)))

    else:
        enrollment = CourseEnrollment(student=user, course=course)
        enrollment.save()

    return redirect(url_for('home'))


def cross_check_dependencies(student: User, course: Course) -> Set[Course]:
    student_courses = set(ce.course for ce in student.courses)
    dependee_courses = set(cd.dependee for cd in course.dependees)

    return dependee_courses - (student_courses & dependee_courses)

application/users/views.py
from flask import Blueprint, render_template, request, session, flash, redirect

from .models import User
from application.courses.models import CourseEnrollment, Course


users = Blueprint('users', __name__, url_prefix='/users')


@users.route('/login', methods=['POST'])
def login():
    username = request.form.get('username')
    password = request.form.get('password')

    select = User.select().where(User.username == username)
    flash_msg = ('Invalid credentials.', 'error')

    if select.count() != 0:
        u: User = select.first()

        if u.password == password:
            session['current_user'] = {'id': u.pk, 'role': u.role}
            flash_msg = ('Welcome back!',)

    flash(*flash_msg)

    return redirect('/')


@users.route('/logout')
def logout():
    session.pop('current_user', None)
    flash('Logged out successfully.')
    return redirect('/')


def student_home():
    return render_template(
        'users/student_home.html.j2',
        courses=Course.select().join(CourseEnrollment)
            .where(CourseEnrollment.student == session['current_user']['id']))


def professor_home():
    return render_template('users/professor_home.html.j2')


def staff_home():
    return render_template('users/staff_home.html.j2')

application/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>El Niño</title>

  <!-- Bootstrap core CSS -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/static/css/heroic-features.css" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/style.css">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">El Niño</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home
            </a>
          </li>
          {% if session.current_user %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.logout') }}">Log out</a>
          </li>
          {% endif %}
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>

  {% for cat, msg in get_flashed_messages(True) %}
    <div class="row">
      <div class="{{ cat }} col-md-12">{{ msg }}</div>
    </div>
  {% endfor %}

  <!-- Page Content -->
  <div class="container">{% block content %}{% endblock %}</div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

application/templates/courses/course_view.html.j2
{% extends "base.html.j2" %}

{% block content %}
    <header class="jumbotron my-4">
      <h1 class="display-3">El Niño Student System</h1>
      <p class="lead">
        {{ course.name }}<br/>
        Lecturer: {{ course.professor.username }}<br/>
        Capacity: {{ course.capacity }}<br/>
        Student count: {{ course.student_count }}
      </p>
    </header>

    {% if current_user %}
      {% if is_enrolled %}
        <div>You are enrolled in this course.</div>
      {% elif course.student_count >= course.capacity %}
        <div>This course has reached max capacity.</div>
      {% elif pending_dependencies %}
        <div>You must complete dependencies first: {{ ', '.join(pending_dependencies) }}</div>
      {% else %}
        <div>You can enroll in this course.</div>
      {% endif %}
      <form action="{{ url_for('.course_enroll', id=course.pk) }}" method="POST">
        <button class="btn btn-primary" id="enroll" type="submit">Enroll</button>
      </form>
    {% else %}
      <div>Login to enroll in this course.</div>
    {% endif %}
{% endblock content %}

application/templates/courses/home.html.j2
{% extends "base.html.j2" %}

{% block content %}
    <header class="jumbotron my-4">
      <h1 class="display-3">El Niño Student System</h1>
      <p class="lead">Courses</p>
    </header>

    {% include "courses/includes/course_listing.html.j2" %}
{% endblock content %}

application/templates/courses/includes/course_listing.html.j2
{% for c in courses %}
    {% if loop.index0 % 4 == 0 %}
      <div class="row text-center">
    {% endif %}
        <div class="col-lg-3 col-md-3 mb-4">
            <a href="{{ url_for('courses.course_view', id=c.pk) }}">
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">{{ c.name }}</h4>
                        <p class="card-text"></p>
                    </div>
                </div>
            </a>
        </div>
    {% if loop.index0 % 4 == 3 or loop.last %}
        </div>
    {% endif %}
{% endfor %}

application/templates/home.html.j2
{% extends "base.html.j2" %}

{% block content %}


    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h1 class="display-3">El Niño Student System</h1>
      <p class="lead">A lightweight, user-friendly student system.<br/>Software Quality and Standards</p>
    </header>

    <!-- Page Features -->
    <div class="row text-center">

      <div class="col-lg-6 col-md-6 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">Login</h4>
            <p class="card-text">
                <form action="{{ url_for('users.login') }}" method="post">
                    <p>Username <input id="username" name="username" type="text"></p>
                    <p>Password <input id="password" name="password" type="password"></p>
                    <button class="btn btn-primary" id="submit" type="submit">Submit</button>
                </form>
            </p>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-6 mb-4">
        <div class="card h-100 ">
          <div class="card-body">
            <h4 class="card-title">Group members</h4>
            <p class="card-text"><ul>
                <li>Ahmed</li>
                <li>Fabricio</li>
                <li>Oluwandabira</li>
                <li>Hông</li>
            </ul></p>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->
{% endblock content %}

application/templates/users/student_home.html.j2
{% extends "base.html.j2" %}

{% block content %}
    <header class="jumbotron my-4">
      <h1 class="display-3">El Niño Student System</h1>
      <p class="lead">Student Homepage</p>
    </header>

    <h2>My Courses</h2><br/>
    {% include 'courses/includes/course_listing.html.j2' %}

    <a href="{{ url_for('courses.home') }}" class="btn btn-primary">Enroll into a new course</a>

{% endblock content %}